import type { PlatformTutorialData } from "./types";

export const cohereTutorial: PlatformTutorialData = {
  slug: "cohere-getting-started",
  platformSlug: "cohere",
  title: "Getting Started with Cohere",
  tagline:
    "An enterprise AI company that sells its technology to other businesses — and how a beginner can still get in for free.",
  archetype: "pick-and-setup",
  lastReviewedAt: "2026-09-13",
  changelogUrl: "https://docs.cohere.com/v2/changelog",
  accessTier: "FREE",

  howItWorks:
    "Cohere's documentation describes the motion like this: you sign in, open the Playground, pick a model (the AI \"brain\" that does the actual thinking) from a panel on the right, type into a message box at the bottom, and read the reply. You adjust your wording or switch models and send again, then click through to the code.",

  whatItIs: [
    "Cohere is a Canadian AI company that sells its models to other businesses rather than running a chatbot of its own — the things it makes end up inside other companies' products, not on your phone.",
    "It is still worth a beginner's twenty minutes, because Cohere publishes its current flagship, Command A+, as a file anyone can download from Hugging Face under the Apache 2.0 licence — the licence that lets a business, not just a hobbyist, run it — which almost no other frontier lab does with its best model.",
    "Alongside writing text, Cohere sells narrower models that chat companies mostly don't: one that reorders search results by relevance, one that pulls text out of scanned documents, plus transcription and translation.",
    "You'll find Cohere underneath somebody else's search box.",
  ],

  beforeYouStart: [
    "Signing up is free and self-serve: go to `dashboard.cohere.com`, create an account with Google, GitHub, or an email and password, and Cohere's pricing FAQ says a trial **API key** (a password that identifies your app, and that spends your money) is created for you automatically and shown in the dashboard's \"API Keys\" section. You need to have reached the age of majority where you live to accept the terms.",
    "**You will almost certainly not need to pay while you are learning.** Cohere's pricing table currently lists Command A+ at $0 for both \"API key\" and \"Model download,\" and Cohere's model documentation says that \"for both trial keys and production keys, Command A+ is free until rate limits are reached.\" The models that do cost money are the smaller and narrower ones — Command R at around $0.15 per million **tokens** (a chunk of text, roughly a short word — how AI usage gets counted) of input — and you have to choose them on purpose.",
    "Free here has a contract attached, not just a ceiling. Cohere's pricing page states that trial keys \"are rate limited and are not permitted to be used for production or commercial purposes,\" and its rate-limit docs currently put chat on a trial key at around 20 requests a minute and 1,000 calls a month. So the free key covers learning and prototypes; the moment something you build takes money, it needs a production key, which bills pay-as-you-go and is requested from the Billing and Usage page by an account owner.",
    "Cohere is built for people putting AI inside software, and most of it is reached from code. The part you can reach in a browser is the Playground, which Cohere's docs describe as a message box with a model picker — you may need to check what it actually offers once you are signed in. If you have never used an AI tool at all, an hour with a chatbot from Text & Conversational AI first will make everything here land better, and Cohere will still be waiting.",
  ],

  security: [
    {
      kind: "text",
      text: "Cohere draws its privacy line by account type, not by a setting you can flip. Its privacy policy addresses trial users directly: \"we collect content you submit to the Cohere Products, and outputs generated by the Cohere Products. We may use this input and output data to conduct research and development.\" The free key you are handed at signup puts you on exactly that side of the line.",
    },
    {
      kind: "list",
      label: "What Cohere itself asks of you",
      items: [
        "Keep personal information out of it. The same policy says it in as many words: \"Please do not submit personal information in inputs to the Cohere Products when accessing them on a research platform or as a Trial User.\"",
        "Don't go looking for an opt-out switch. Controlling how Cohere trains on your data is described as something Enterprise Users negotiate, alongside a data processing agreement — a contract term, not a toggle in settings.",
        "If you put a Cohere model in front of other people, Cohere's usage policy (the version published as of 13 September 2026 is dated 21 November 2024) requires your app to \"disclose to the users that they are interacting with an AI system rather than a human.\"",
      ],
    },
    {
      kind: "text",
      text: "None of this is unusual for a developer platform. What is unusual is how plainly Cohere addresses the sentence to you.",
    },
  ],

  triad: {
    bestAt: [
      "Working in languages other than English — Command A+ is documented at 48 languages, including every official EU language",
      "Answering from documents you hand it, with the reply marked up to show which document each claim came from",
      "Being a model you could later run yourself, because the flagship's file is published rather than locked in the service",
    ],
    okayAt: [
      "Being your everyday assistant — the browser surface Cohere documents is a developer test bench",
      "Anything involving pictures — Command A+ takes images as input, but Cohere sells no image generator",
      "Telling you what things will cost: individual models carry public prices, but North and Compass both say only \"Get in touch for custom enterprise pricing\"",
    ],
    avoid: [
      "Reaching for it as your daily chatbot. Cohere's own homepage lists North, Compass, Command, Transcribe, Embed, Rerank, Parse, North Small Translate, Aya and Model Vault — and not one of them is a consumer app you'd open in the morning",
      "Following any Cohere tutorial written before this year. Cohere retired the `command`, `command-light`, `command-r` and `command-r-plus` names on 15 September 2025 and five more models on 4 April 2026, so older sample code names models the service no longer serves",
      "Treating a citation as a fact-check. It tells you which document a sentence came from, not whether that document was right",
    ],
  },

  starterActions: [
    {
      title: "Put Command A+ in the model slot before you try anything else",
      whatItDoes:
        "Open the Playground from the dashboard and choose Command A+ from the model list on the right, rather than accepting whatever is selected by default.",
      whyHere:
        "Most vendor playgrounds sit you on a metered flagship whose weights you will never see, so what you learn about its behaviour is only ever rentable. With Command A+ the thing in the picker and the thing you could run yourself are one model, which is true of neither half of OpenAI's Playground.",
      tweak:
        "Command R and Command R7B are the smaller, metered ones; there is no reason to pick them while you are learning.",
    },
    {
      title: "Ask it in a language that isn't English",
      prompt:
        "Answer this in Polish, then give me an English back-translation underneath so I can check it: [your question]",
      whyHere:
        "Cohere sells two more models whose entire job is translation — command-a-translate across 23 languages and North Small Translate across more than 50. Anthropic, by contrast, ships no dedicated translation model and publishes no supported-language count to check against.",
      tweak:
        "Swap Polish for whichever language you actually need. The back-translation is the part that tells you whether to trust it.",
    },
    {
      title: "Hand it a document and make it show its working",
      prompt:
        "Here is a document: [paste it]. Answer this question using only that document, and after each sentence of your answer, quote the exact line you took it from: [your question]",
      whyHere:
        "When you supply documents through Cohere's chat interface, its documentation says the reply comes back with a citations object naming which document supports a claim and marking \"the start and end fields, which are spans that tell us the location of the supported claim inside the reply.\" Grounding is a return value here, not a habit you have to coax out of the model; OpenAI's chat completions return no per-span citation object for documents you supply. The docs describe that object in the API response, though — whether the Playground draws those spans on screen is not something they demonstrate, which is why this asks for the quotes in plain text instead.",
      tweak:
        "A rental agreement, a policy document, a long email thread — anything where \"where did you get that?\" is the question you'd ask a person.",
    },
    {
      title: "Read the Rerank row on the pricing page and work out what it is for",
      whatItDoes:
        "Look at the retrieval models on cohere.com/pricing — Rerank 4 Fast at around $2 per million tokens, Rerank 4 Pro at around $2.50.",
      whyHere:
        "Reranking is sold here as a model in its own right, with its own price, doing nothing else. Neither Anthropic nor OpenAI sells a standalone reranking model, so a team with a bad search box has to improvise one out of a chat model.",
    },
    {
      title: "Check which kind of key you are holding before you build on it",
      whatItDoes:
        "Open the dashboard's \"API Keys\" section and confirm the key sitting there is the trial key created at signup, not a production key.",
      whyHere:
        "Cohere is one of the few platforms where the free key's ceiling is contractual as well as numeric, and where a production key is a separate object rather than a card on file. There is no equivalent wrong-key state at OpenAI, where a key is one kind of object with a balance behind it.",
    },
  ],

  pitfalls: [
    "Landing on cohere.com, seeing \"Request a demo\" and \"Sign in,\" and concluding there is no way in. The free self-serve signup lives at `dashboard.cohere.com` and is not advertised on the front page at all.",
    "Reading the \"$0\" next to Command A+ as \"unlimited.\" It is a price, not a quota — the rate limits sit on top of it and are what you will actually run into.",
    "Confusing the two different frees. The Apache 2.0 licence on the downloaded Command A+ file permits commercial use; the free trial key explicitly does not. Same model, two different permissions, and it is the key that carries the restriction.",
    "Expecting the Playground to cover the product. Cohere's docs describe it as supporting Chat and Embed — so Rerank, Parse and Transcribe, the models that most distinguish Cohere from a chat company, are the ones you cannot click your way into.",
    "Trying to add a colleague and finding you can't. Cohere's FAQ states that \"every account begins as a personal account,\" and that you \"will not be able to add other members until you become part of an organization.\"",
  ],

  whereToNext: [
    { label: "AI APIs & Developer Services", categorySlug: "ai-apis-developer-services" },
    { label: "Text & Conversational AI", categorySlug: "text-conversational-ai" },
    { label: "Local & Open-Source AI", categorySlug: "local-open-source-ai" },
  ],
};
