import type { PlatformTutorialData } from "./types";

export const scholarcyTutorial: PlatformTutorialData = {
  slug: "scholarcy-getting-started",
  platformSlug: "scholarcy",
  title: "Getting Started with Scholarcy",
  tagline: "Turn a research paper into a summary card you can actually skim.",
  archetype: "pick-and-setup",
  lastReviewedAt: "2026-09-15",
  accessTier: "FREE",

  howItWorks:
    "You drag a PDF onto the page, paste a link, or click a browser button while a paper is open. Scholarcy reads the document and hands back a card: the main finding, the key claims, the numbers, the references. You scroll it, jump to the bit you want, and swap the summary to a different level of detail.",

  whatItIs: [
    "Scholarcy is a summarizer built specifically for academic papers. You give it a paper; it gives you back a **Summary Flashcard** (Scholarcy's name for the card it builds — one paper, one card, split into sections you can jump between).",
    "It is not a chatbot. There is no message box and nothing to write — you import a document and pick from a short list of menus. That makes it far narrower than a general AI assistant, and far quicker at the one thing it does.",
    "There are two front doors. The free **Article Summarizer** lives at `library.scholarcy.com/try` and summarizes on the spot. **Scholarcy Plus** is a paid Library at `library.scholarcy.com` where imported papers stay put, with notes, highlights and collections.",
  ],

  beforeYouStart: [
    "The free tool needs no card, and its entry link goes to a try page rather than a signup page, so you should be able to drop a PDF in and see what comes out before deciding anything — though you may be asked to sign up after the first one. Scholarcy Plus is **$9.99/month or $90/year**, and starts with a one-week free trial that bills automatically at the end unless you cancel. Scholarcy's terms say it does not refund subscription fees unless legally required, so cancel before the week is up if you are only testing.",
    "**How much you get free is stated three different ways on Scholarcy's own site, so verify it in the app before you plan around it.** The pricing comparison table says \"Limit of 10 summaries\"; the FAQ further down that same page says \"up to 1 summary per day\"; the Article Summarizer page's own comparison table says \"Limit of 3 summaries per day\". All three were live on 15 September 2026. The vendor's pages disagree with each other, so take the free tier as somewhere in that range — a few summaries a day at most, enough to evaluate the tool and not enough to run a literature review through — and confirm the current number once you are in.",
    "File size caps at **11MB on a free account and 50MB on a paid one**. Scholarcy is built for one paper or one book chapter at a time, not whole books — its own example is a 400-page textbook reduced to a 400-word summary, one word per page. Split anything long into chapters before you upload.",
    "**Language support is partial in a way that matters.** Scholarcy says it summarizes articles in most European languages but does not publish the list, so whether yours is covered is something you will have to test with one paper. Only some of the output stays in the original either way: the highlights, the summary, the comparative analysis and the full text come back in the paper's own language, while the plain-language Synopsis and every enhanced summary mode are **rewritten in English** regardless of what you uploaded, because of the outside services Scholarcy routes them through. If you are reading a Spanish or German paper and want a Spanish or German summary, the most readable outputs will not be.",
  ],

  security: [
    {
      kind: "text",
      text: "What happens to your PDF is the question worth asking here, and Scholarcy answers it concretely: its FAQ states it never stores imported documents for long-term use and deletes the PDF once the flashcard is built, and it says it stores data on third-party servers in Europe. Its privacy policy — effective 1 January 2020, last revised 7 February 2024 — is the version in force today.",
    },
    {
      kind: "list",
      label: "Worth knowing before you upload",
      items: [
        "The browser extension reads the text or the URL of the page you are on; that is how it produces a summary, so while it is active it sees what you are reading.",
        "The Chrome Web Store listing discloses that the extension handles location and website content, and states the data is not sold to third parties or used for unrelated purposes.",
        "Parts of the summary are generated by outside services Scholarcy does not own, so your text does not stay inside Scholarcy alone.",
        "Neither the terms of service nor the privacy policy says whether your uploads are used to improve the service. They are silent on it, which is not the same as a promise that they are not, so treat silence as silence.",
        "Scholarcy says it uses \"end-to-end encryption methods\" but does not define what that covers; it is not the same claim as end-to-end encrypted messaging and should not be read as one.",
      ],
    },
    {
      kind: "text",
      text: "Uploading a paywalled paper you legitimately have access to is fine by Scholarcy's account: it describes itself as a summarizing and management tool rather than a distribution service and does not keep the PDF. What you may do with the result is narrower than people assume — the terms grant you a perpetual, royalty-free licence over the output **for personal use only** and bar commercial distribution, and your library's or publisher's own licence still governs the source paper.",
    },
  ],

  triad: {
    bestAt: [
      "Deciding in two minutes whether a paper is worth reading properly",
      "Pulling the claims, numbers, figures and tables out of a dense results section",
      "Turning a paper's reference list into a reading list — it links each citation out to a freely readable version where it can find one",
      "Working through a stack of papers you have already gathered, where you want the same questions asked of each one",
    ],
    okayAt: [
      "Book chapters — good one chapter at a time, poor on anything book-length",
      "Online articles and YouTube videos — supported, but the extraction is tuned for academic structure, so a news piece or a talk yields a thinner card than a paper does",
    ],
    avoid: [
      "**Trusting how confident the card sounds.** Scholarcy's own page says its output is factually correct and traceable to the source; its terms of service disclaim any warranty that the service will meet your requirements. Both can be true, because the thing that goes missing is rarely a fact — it is the hedge around it. \"The effect was small, in one sample, and needs replication\" compresses into a flat claim, and the flashcard gives you no signal that a qualifier was dropped. Open the sentence a claim came from before you repeat it.",
      "**Citing or quoting a paper you have only met as a flashcard.** The card is an index into the paper — it tells you where to look. It is not a source in its own right, and a quotation lifted from a summary is a quotation from Scholarcy.",
      "**Looking for papers with it.** Scholarcy only ever works on documents you hand it; it does not search, and it will not tell you which papers exist. If you do not already know what you need to read, this is the wrong end of the process.",
    ],
  },

  starterActions: [
    {
      title: "Summarize a paper you already know well",
      whatItDoes:
        "Open the free Article Summarizer at `library.scholarcy.com/try`, drag in a PDF of a paper whose conclusions you could already state out loud, and read the card against your own memory of it.",
      whyHere:
        "Scholarcy's card is broken into fixed, named sections — highlights, synopsis, claims, figures, references — rather than one block of prose, so a paper you know lets you audit each section separately and learn which ones you can rely on. Against a paper you have not read, a dropped caveat is invisible.",
      tweak:
        "Then try one from outside your field and notice how much harder the card is to sanity-check.",
    },
    {
      title: "Find the Enhance menu before you decide the summary is wrong",
      whatItDoes:
        "On a generated summary, click **Enhance** and pick a reading style: `School level`, `General reader`, `Bulleted list`, `Undergrad level`, `One liner` or `Researcher`. You can also choose **Specific topics** and select up to five keywords to point the summary at.",
      whyHere:
        "Six named styles and five keywords, chosen from menus, are the whole of Scholarcy's steering. Check what you actually get, too: Scholarcy's pricing table lists enhanced summaries as a Scholarcy Plus feature while its own FAQ explains Enhance as though any user can reach it. The two vendor pages disagree, which is not resolvable from outside, so the app is the tiebreaker.",
      tweak:
        "Scholarcy describes these as reading styles rather than lengths, which suggests the shorter ones drop categories of detail rather than merely compressing them — run one paper at two styles and compare before you rely on the short one.",
    },
    {
      title: "Mine the references, not just the summary",
      whatItDoes:
        "Scroll to the references section of the card. Scholarcy tries to link each cited work out to a version you can read for free, so you can open the papers this one is built on without going back through a subscription wall.",
      whyHere:
        "Chasing down freely readable copies of the exact works cited is a step Scholarcy runs as part of building the card — its own extension listing describes linking to open versions of each citation. Tools that suggest \"related papers\" are searching a database for things like your paper; this is the actual bibliography of the paper in front of you.",
      tweak:
        "Start from a recent review article — its reference list is a ready-made syllabus.",
    },
    {
      title: "Install the extension and summarize without downloading anything",
      whatItDoes:
        "Add the Scholarcy extension from the Chrome, Edge or Firefox store — Safari is listed as coming soon — then click it while a paper is open in your browser. It returns the card without you leaving the page.",
      whyHere:
        "The extension and the upload path are not interchangeable, and knowing which one failed saves you a wasted conclusion. The extension works from whatever the page will give it, so a subscription-only PDF that summarizes perfectly well after you download it can come back empty through the extension. When that happens, download the PDF and upload it instead of assuming the paper cannot be summarized.",
      tweak:
        "The extension appears to have some free allowance of its own, since the Chrome Web Store listing sells \"unlimited extension use\" as a paid benefit — but Scholarcy does not publish what the free limit is, or whether it draws on the same allowance as the web summarizer, so watch what it lets you do.",
    },
    {
      title: "Line several papers up side by side (Plus only)",
      whatItDoes:
        "With Scholarcy Plus, import several papers into the Library and generate a **Literature Matrix** — a grid that puts the papers in rows and what each one did and found in columns. Free accounts cannot create one.",
      whyHere:
        "Paying turns on this one feature, and the honest test is simple: the matrix is built only from papers you imported yourself, so it is a filing system rather than a discovery one. If you already have the stack, it earns its money; if you are still assembling it, nothing here will help you find the next paper.",
    },
  ],

  pitfalls: [
    "**An empty card is a known outcome, not something you did wrong.** Scholarcy keeps a dedicated help article for imports that finish with a blank record. The usual causes: the PDF is a scan, so its pages are pictures of text with nothing to extract; the URL is behind a subscription wall and returns nothing; or the file is too big or too image-heavy. For a scan, run it through text-recognition software first — Scholarcy does not do that step for you.",
    "**On the free tool, closing the tab loses the summary.** There is no library holding it and saving flashcards is a Scholarcy Plus feature; free users can export one flashcard at a time, and paid users up to 100 at once. Export as you go, or plan to re-run the paper.",
    "**Read the highlight-colour key once.** Scholarcy colour-codes the terms, claims and findings it pulls out and documents the scheme in its help centre, but nothing in the interface tells you that the colours mean different things. Until you look it up the card reads as undifferentiated highlighting and you lose most of what it is signalling.",
    "**The marketing numbers on Scholarcy's own site do not agree with each other** — 600,000 users on one page, 400,000 on another. It is not a reason to distrust the summaries, but it is a reason to confirm any number you are planning around inside the app rather than taking it off a landing page.",
  ],

  whereToNext: [
    { label: "Document and PDF tools", categorySlug: "document-pdf-processing" },
    { label: "Learning tools", categorySlug: "education-learning-ai" },
    { label: "AI chatbots", categorySlug: "text-conversational-ai" },
  ],
};
